# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from rngesus import Lotto


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.balance = 0
        MainWindow.setObjectName("Lottos")
        MainWindow.resize(1221, 610)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 200, 131, 71))
        self.pushButton.setObjectName("pushButton")
        #
        self.pushButton.clicked.connect(self.mixClicked)
        #
        self.comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 140, 51, 27))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(50, 100, 121, 17))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(500, 150, 41, 27))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(500, 190, 41, 27))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(500, 230, 41, 27))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(500, 270, 41, 27))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(500, 310, 41, 27))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(500, 350, 41, 27))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(470, 110, 111, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(620, 360, 141, 27))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(630, 330, 67, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(660, 160, 41, 27))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(620, 130, 131, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(770, 370, 67, 17))
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox.setGeometry(QtCore.QRect(200, 100, 231, 22))
        self.checkBox.setObjectName("checkBox")
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit.setGeometry(QtCore.QRect(920, 100, 261, 421))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(930, 70, 91, 17))
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 180, 51, 27))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_3.setGeometry(QtCore.QRect(70, 220, 51, 27))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_4.setGeometry(QtCore.QRect(70, 260, 51, 27))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_5.setGeometry(QtCore.QRect(70, 300, 51, 27))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_6.setGeometry(QtCore.QRect(70, 340, 51, 27))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(620, 460, 141, 27))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(630, 430, 121, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(770, 470, 67, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(620, 270, 141, 27))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(630, 240, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(770, 270, 67, 17))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1221, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuLottos = QtWidgets.QMenu(self.menuBar)
        self.menuLottos.setObjectName("menuLottos")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuLottos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lottos"))
        self.pushButton.setText(_translate("MainWindow", "Draw!"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox.setItemText(48, _translate("MainWindow", "49"))
        self.label.setText(_translate("MainWindow", "Choose numbers"))
        self.label_2.setText(_translate("MainWindow", "Numbers drawn"))
        self.label_3.setText(_translate("MainWindow", "Prize"))
        self.label_4.setText(_translate("MainWindow", "Matching numbers"))
        self.label_5.setText(_translate("MainWindow", "zł"))
        self.checkBox.setText(_translate("MainWindow", "Pseudo Random Distribution"))
        self.label_6.setText(_translate("MainWindow", "Last draws"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_2.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_2.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_2.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_2.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_2.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_2.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_2.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_2.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_2.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_2.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox_2.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox_2.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox_2.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox_2.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox_2.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox_2.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox_2.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox_2.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox_2.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox_2.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox_2.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox_2.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox_2.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox_2.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox_2.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox_2.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox_2.setItemText(48, _translate("MainWindow", "49"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_3.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_3.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_3.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_3.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_3.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_3.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_3.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_3.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_3.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_3.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_3.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_3.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox_3.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox_3.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox_3.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox_3.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox_3.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox_3.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox_3.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox_3.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox_3.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox_3.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox_3.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox_3.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox_3.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox_3.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox_3.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox_3.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox_3.setItemText(48, _translate("MainWindow", "49"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_4.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_4.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_4.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_4.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_4.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_4.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_4.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_4.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_4.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_4.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_4.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_4.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox_4.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox_4.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox_4.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox_4.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox_4.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox_4.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox_4.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox_4.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox_4.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox_4.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox_4.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox_4.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox_4.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox_4.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox_4.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox_4.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox_4.setItemText(48, _translate("MainWindow", "49"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_5.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_5.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_5.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_5.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_5.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_5.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_5.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_5.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_5.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_5.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_5.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_5.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_5.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_5.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_5.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_5.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_5.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_5.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_5.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox_5.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox_5.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox_5.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox_5.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox_5.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox_5.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox_5.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox_5.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox_5.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox_5.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox_5.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox_5.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox_5.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox_5.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox_5.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox_5.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox_5.setItemText(48, _translate("MainWindow", "49"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_6.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_6.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_6.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_6.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_6.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_6.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_6.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_6.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_6.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_6.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_6.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_6.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_6.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_6.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_6.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_6.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_6.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_6.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_6.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_6.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox_6.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox_6.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox_6.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox_6.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox_6.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox_6.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox_6.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox_6.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox_6.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox_6.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox_6.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox_6.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox_6.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox_6.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox_6.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox_6.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox_6.setItemText(48, _translate("MainWindow", "49"))
        self.label_7.setText(_translate("MainWindow", "Total win/loss"))
        self.label_8.setText(_translate("MainWindow", "zł"))
        self.label_9.setText(_translate("MainWindow", "Total pot"))
        self.label_10.setText(_translate("MainWindow", "zł"))
        self.menuLottos.setTitle(_translate("MainWindow", "Lottos"))

    def mixClicked(self):
        lotto = Lotto()
        if not self.checkBox.isChecked():
            lotto.mix()
            self.lineEdit.setText(str(lotto.pool[0]))
            self.lineEdit_2.setText(str(lotto.pool[1]))
            self.lineEdit_3.setText(str(lotto.pool[2]))
            self.lineEdit_4.setText(str(lotto.pool[3]))
            self.lineEdit_5.setText(str(lotto.pool[4]))
            self.lineEdit_6.setText(str(lotto.pool[5]))
            numbers = []
            numbers.append(int(self.comboBox.currentText()))
            numbers.append(int(self.comboBox_2.currentText()))
            numbers.append(int(self.comboBox_3.currentText()))
            numbers.append(int(self.comboBox_4.currentText()))
            numbers.append(int(self.comboBox_5.currentText()))
            numbers.append(int(self.comboBox_6.currentText()))
            win = lotto.checkWin(numbers)
            self.lineEdit_8.setText(str(win))
            pot = lotto.randomizeTotalPrize()
            self.lineEdit_10.setText(str(pot))
            prize = lotto.calculatePrize(win, pot)
            self.lineEdit_7.setText(str(prize))
            self.textEdit.append(str(lotto.pool) + " prize " + str(prize))
            self.balance += prize
            self.balance -= 3
            self.lineEdit_9.setText(str(self.balance))
        else:
            lotto.PRDmix()

